### ISSUE TITLE
Error: Template installation failed: Illegal template structure, unknown path src

### ISSUE THREAD

**Issue by monkeymars** [Deathwish98/strapi-medusa-template#2]
found this issue when trying to install this template. is it because of incorrect folder structure?

`➜  medusa npx create-strapi-app strapi-medusa --template https://github.com/Deathwish98/strapi-medusa-template.git
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at /Users/admin/Dev/kultara/medusa/strapi-medusa.
Creating files.
Installing Deathwish98/strapi-medusa-template template.
Error: ⛔️ Template installation failed: Illegal template structure, unknown path src
    at createProject (/Users/admin/.config/yarn/global/node_modules/strapi-generate-new/lib/create-project.js:79:15)
    at async createQuickStartProject (/Users/admin/.config/yarn/global/node_modules/strapi-generate-new/lib/create-quickstart-project.js:22:3)`

npm v6.14.9
node v14.19.1
strapi v3.6.0-beta.5

**Comment by Deathwish98** [comment]
@Kyle772

**Comment by Inoir** [comment]
Seems this template is updated for v4 but the plugin not?!
Unusable together :/

**Comment by lithiumlab** [comment]
My thoughts exactly. The main version of the template is updated to v4 but seems the plugin is not.
https://github.com/Deathwish98/medusa-plugin-strapi/issues/1

It is impossible right now from tutorials to get the syncing up.
While creating a v3 strapi the template fails.
While creating a v4 strapi the plugin fails.

**Comment by ghost** [comment]
Hey guys,

if it helps for anyone here: I've worked on a working version for me for strapi version 4.4.5

Feel free to test it
https://github.com/ai-ecom-akram/strapi-medusa-template

**Comment by thomcrielaard** [comment]
I'm working on a version for Strapi 4.15.0, please let me know if you have any errors (I'm really unfamiliar with Medusa, so I just refactored everything I needed and what I think should be refactored, but would love to help the community out). 

https://github.com/thomcrielaard/strapi-medusa-template.git
